### ISSUE TITLE
Add a "Load More Posts" Button

### ISSUE THREAD

**Issue by knightspore** [knightspore/unredd#1]
It would be nice to have the ability to add another 25 posts using a button or when the user scrolls to the end of the page.

**Comment by SriCoD** [comment]
can i be assigned, i can work well on it

**Comment by knightspore** [comment]
@SriCoD assigned to you, cheers!

**Comment by knightspore** [comment]
Issue is open for anyone to take

**Comment by SriCoD** [comment]
I'm done with it, will update with it within a day

**Comment by mihailot01** [comment]
I added a "Load More Posts" Button, should I create a new Pull Request?

**Comment by knightspore** [comment]
Issue closed with PR #2

https://github.com/knightspore/unredd/pull/2
